### PR TITLE
Remove `where` from transform_t

### LINKED ISSUE #27: Remove `where` parameter from transform lambda
**Version:** 1.0.0

The `transform_t` codec takes a function with two arguments to transform the decoded value. I propose that we remove the second parameter, `where`. It is there so that there is something to pass into the `decode_exception` constructor. It makes the function more _boilerplatey_ and also means that you cannot easily use transform functions not specifically written for our JSON library, e.g., using an `int2str` function that takes an `int` and returns a `std::string`.

The original use case for the `where` parameter can be handled by catching any `decode_exception` thrown by the transform function and just setting the where parameter as appropriate before re-throwning the exception.

### PR DESCRIPTION
**Pull request by punchfox**
Fixes #27.

### CODE REVIEW

**Comment by punchfox** [comment]
I need to review the documentation as well.

File: include/spotify/json/decode_exception.hpp [hunk 1]
```diff
@@ -31,8 +31,9 @@ namespace json {
 class decode_exception final : public std::runtime_error {
  public:
   template <typename string_type>
-  json_never_inline decode_exception(const string_type &what, const size_t offset)
-      : runtime_error(what), _offset(offset) {}
+  json_never_inline explicit decode_exception(const string_type &what, const size_t offset = 0)
```
Comment (fxb) [inline include/spotify/json/decode_exception.hpp]: It seems like this default argument was just added for a single test case. I'd prefer not having it here, but instead just set offset to 0 in the test case.

Comment (punchfox) [inline include/spotify/json/decode_exception.hpp]: It was actually added so that the user's decode transform function could throw decode_exceptions without specifying the JSON offset.

Comment (fxb) [inline include/spotify/json/decode_exception.hpp]: Okay, makes sense.
